#!/bin/sh

set -ex

# Validate the root module.
golangci-lint run --new-from-rev=origin/main ./...
go build -v ./...
go test ./... -failfast

## Validate the examples/devdata_cli sub-module.
cd examples/devdata_cli
golangci-lint run --new-from-rev=origin/main ./...
go build -v ./...
go test ./... -failfast
cd -

