linters:
  enable:
    - asciicheck # Simple linter to check that your code does not contain non-ASCII identifiers.
    - bodyclose # Checks whether HTTP response body is closed successfully.
    - gci # Control golang package import order and make it always deterministic.
    - godot # Check if comments end in a period.
    - misspell # Finds commonly misspelled English words in comments.
    - rowserrcheck # Checks whether Err of rows is checked successfully.
    - sqlclosecheck # Checks that sql.Rows and sql.Stmt are closed.
    - goheader # Checks is file header matches pattern.

linters-settings:
  goheader:
    values:
      const:
        COMPANY: Searis AS
      regexp:
        ANY_AUTHOR: (, .*)*
    template-path: .go-header.tmpl
