name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for go-header check.

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            examples/devdata_cli/go.sum
        id: go

      - name: Verify go modules up to date
        run: go mod tidy -diff

      - name: Test (main module)
        run: go test -race ./...

      - name: Lint (main module)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true # Required for go-header check
          args: --timeout=10m

      - name: Test example/devdata_cli (sub module)
        run: cd ./examples/devdata_cli && go test -race ./...

  integration_test:
    name: Integration test
    strategy:
      matrix:
        # boolean values are cast to indices
        environments: ${{ fromJSON('[["staging"], ["staging", "production"]]')[github.ref == 'refs/heads/main'] }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environments }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            examples/devdata_cli/go.sum
        id: go

      - name: Test (main module)
        run: go test -race ./test/...
        env:
          CLARIFY_USERNAME: ${{ secrets.CLARIFY_USERNAME }}
          CLARIFY_PASSWORD: ${{ secrets.CLARIFY_PASSWORD }}
          CLARIFY_ENDPOINT: ${{ secrets.CLARIFY_ENDPOINT }}
